### ISSUE TITLE
LeaderBoard Datenübermittlung

### ISSUE THREAD

**Issue by derPascalD** [Only-OGs/Server#11]

**Comment by derPascalD** [comment]
posi: 1-8
name: ID Namen der Spieler
time: Minuten:Sekunden:Millisekunden

[
{"posi": 1, "name": Pascal,"time": 00:46:56},
{"posi": 2, "name": LOL,"time": 00:47:00},
{"posi": 3, "name": Phil,"time": 00:47:50},
{"posi": 4, "name": Olli,"time": 00:49:50},
{"posi": 5, "name": Pakkal,"time": 00:50:00},
{"posi": 6, "name": Test,"time": 00:53:00},
{"posi": 7, "name": Jan,"time": 00:59:00},
{"posi": 8, "name": Simon,"time": 01:03:00},
]  

Die Reihenfolge die uns geschickt wird , sollte schon Aufwärts je nach posi sortiert sein.

Das Beispiel wär mit 8 Spielern. Das JSON Array sollte immer zwischen 2 - 8 JSON Objekte beinhalten.

Wir würden das Event _get_leaderboard_ anlegen, worüber du uns das JsonArray schicken kannst.

**Comment by oliadler** [comment]
Funktioniert - siehe hier:
![image](https://github.com/Only-OGs/Server/assets/112949626/424cf7b2-1cda-444f-8876-61e220d84c22)

**Comment by Pascal378** [comment]
Done :)
