### ISSUE TITLE
Game Leave Event

### ISSUE THREAD

**Issue by derPascalD** [Only-OGs/Server#12]

**Comment by derPascalD** [comment]
Wir bräuchten noch ein Event was wir auslösen würden, wodurch du weißt das wir das Game verlassen haben und zurück ins Hauptmenü befördern, um uns aus dem Spiel zu nehmen. Wir würden dafür das Event

 **game_leave**

erstellen, was wir dann auslösen sobald wir durch unser Menü das Spiel verlassen.

**Comment by Pascal378** [comment]
Es reicht wenn ihr ein game_leave Event auslöst ohne irgendwelche Daten zu senden. Den Rest mache ich dann.

**Comment by oliadler** [comment]
Ist bei uns eingebaut :)

**Comment by Pascal378** [comment]
Done :)
