### ISSUE TITLE
Eigenen Server aufsetzen und Connection bereitstellen

### ISSUE THREAD

**Issue by oliadler** [Only-OGs/Server#2]
- Benutzer anlegen und Zugriffsrechte gewähren
- öffentliche IP-Adresse für die Kommunikation bereitstellen, sowie die Codierung angeben die benötigt wird, um sich mit dem Server zu verbinden (Base64-Codierung eventuell?)
-

**Comment by araqs11** [comment]
Hat erstmal eine niedrige Prio, ich denke wir könnten das Issue erstmal schließen
