### ISSUE TITLE
[Lobby Bereich] Interaktion zwischen Server und Client erstellen

### ISSUE THREAD

**Issue by derPascalD** [Only-OGs/Server#3]

**Comment by Pascal378** [comment]
Können wir das closen mittlerweile? Wir haben ja die Lobby soweit fertig funktional, das einzige was fehlt ist der Spielstart und der damit einhergehende Wechsel über von der Lobby ins Spiel. Würde das als gesonderten Issue behandeln wenn das für dich euch okay ist?

Server-Seitig steht zumindest erstmal alles, auch wenn ein wenig Refactoring noch nötig ist umd das ganze schöner zu machen.
