### ISSUE TITLE
Wechsel auf Rootserver

### ISSUE THREAD

**Issue by oliadler** [Only-OGs/Server#4]
Hallo zusammen,
ich gehe mal davon aus, dass wir diesen Schritt (siehe Titel) nach dem MVP implementieren werden, richtig?
Mit dem lokalen Server ist das testen aktuell auch deutlich einfacher. Habt ansonsten dazu alternativ andere Gedanken? :)

**Comment by Pascal378** [comment]
Rein theoretisch sollte es jetzt schon klappen mit den nötigen Settings, habs lokal getestet da liefs aber nicht. Kann natürlich an meinem Router und vielen Einstellungen  liegen, vielleicht können wir das ja heute mal kurz auf dem root testen, @araqs11 ? Der ist ja dafür konfiguriert Verbindungen von und nach außen zuzulassen. Dann sind wir schlauer :)

**Comment by Pascal378** [comment]
Läuft, klappt, funktioniert!
