### ISSUE TITLE
Datenübermittlung für die Autos

### ISSUE THREAD

**Issue by oliadler** [Only-OGs/Server#7]
So haben wir uns das JSON überlegt.
Beispiel:

[
  {
    "car1": {
      "userid": "id1",
      "sprite": "car1.jpg",
      "x": 42,
      "z": 45,
      "type": "npc or not"
    }
  },
  {
    "car2": {
      "userid": "id2",
      "sprite": "car2.jpg",
      "x": 42,
      "z": 45,
      "type": "npc or not"
    }
  }
]

Diese Daten werden benötigt für das Rendern eines Autos über den Server

**Comment by derPascalD** [comment]
Ticket würde ich mit annehmen

**Comment by Pascal378** [comment]
Ist damit sichergestellt das bei beiden Clients alles immer an der selben Position ist?

**Comment by araqs11** [comment]
Format für die Start-Daten soll wie folgend aussehen:
[offset, position]

offset darf von -1 bis 1 gehen,
position sollte irgendwo zwischen 0-1000 liegen denke ich mal, ich muss mich da mit jan nochmal besprechen

Beispiel:

[
   ["offset": -1, "pos": 0],
   ["offset": 0, "pos":100],
   ["offset": 1, "pos":200]
]

**Comment by jansc03** [comment]
Die Start Positionen von unterschiedlichen Autos dürfen glaube ich nicht innerhalb eines Segments sein oder Auf einander folgen.
Deshalb würde ich empfehlen die pos: Werte 0 , 400 , 800 sein zu lassen

**Comment by jansc03** [comment]
[
["offset": -0.66, "pos": 0,"id": Serverpascal],
["offset": 0, "pos":0,"id": simon],
["offset": 0.66, "pos":0,"id": olli]
["offset": -0.66, "pos": 400,"id": phillip],
["offset": 0, "pos":400,"id": timo],
["offset": 0.66, "pos":400,"id": joachim69]
["offset": -0.66, "pos": 800,"id": Javapascal],
["offset": 0, "pos":800,"id": jan],
]
Ein Beispiel für 8 Startpositionen
