### ISSUE TITLE
Straßen generierung

### ISSUE THREAD

**Issue by araqs11** [Only-OGs/Server#8]
Die Clients brauchen folgendes Format:
[Länge des Abschnitts, Kurvenstärke, Hügelhöhe]

Länge des Abschnitts kann von 50 bis 200 variieren
Kurvenstärke von -6 bis 6 variieren
Hügelhöhe von -60 bis 60 variieren

Hier einmal eine Beispiel strecke
{
    [100, 0, 60],
    [50, 0 ,0],
    [100, 0, -60],
    [90, 4, 0],
    [50, 0, 0],
    [90, -4, 0]
}

**Comment by Pascal378** [comment]
Gotcha :)

**Comment by oliadler** [comment]
[
{ length: "100",
  curves: "0",
  height: "60"
},
{ length: "50",
  curves: "0",
  height: "0"
},
{ length: "100",
  curves: "0",
  height: "-60"
}

...
]

So habe ich mir das vorgestellt.

**Comment by Pascal378** [comment]
Done
