### ISSUE TITLE
Auto Daten generieren

### ISSUE THREAD

**Issue by derPascalD** [Only-OGs/Server#9]
Die Clients brauchen folgendes Format:
[(int)CarTexture, (float)offset, (double)z]

Bei CarTexture brauch ich den Index Wert des Spielers. Um für jedes Auto eine andere Texture zu setzen.
Offset ist -1 bis 1 alles Inklusive.

Hier einmal eine Beispiel strecke
{
[1, -2, 60],
[1, -2, 60],
[1, -2, 60],
[1, -2, 60],
[1, -2, 60],
[1, -2, 60],
[1, -2, 60],
[1, -2, 60]
}

**Comment by Pascal378** [comment]
Done :)
